import Head from "next/head";
import Header from "../components/Header";
import { useSession, getSession } from "next-auth/react";
import Login from "../components/Login";

export async function getServerSideProps(context) {
	return {
		props: {
			session: await getSession(context),
		},
	};
}

export default function Home({ session }) {
	// const { data: session } = useSession();
	const sess = {
		username: 'fadeelgbaiye',
		image: "https://windows10spotlight.com/wp-content/uploads/2018/10/0666a2eb7b483900e65de263a3c6ebc6-768x432.jpg"

	}

	if (!sess) return <Login />;
	return (
		<div>
			<Head>
				<title>Facebook</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
		</div>
	);
}
